build:
    image: gitlab/dind

    before_script:
        - apt-get update
        - apt-get install -y sshpass
        - docker pull pritunl/archlinux
        - docker run --name eloquentos -itd --privileged -v ${PWD}:/mnt pritunl/archlinux /bin/bash
        - docker exec eloquentos cp /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.backup
        - docker exec eloquentos sed -i 's/^#Server/Server/' /etc/pacman.d/mirrorlist.backup
        - docker exec eloquentos /bin/sh -c "rankmirrors -n 6 /etc/pacman.d/mirrorlist.backup > /etc/pacman.d/mirrorlist"
        - docker exec eloquentos pacman -S archiso cdrkit --noconfirm
        - docker exec eloquentos pacman-key --add /mnt/sign-key
        - docker exec eloquentos pacman-key --lsign-key eloquentos@nimbusoft.co.uk
        - docker exec eloquentos mkdir /run/shm

    script:
        - docker exec eloquentos /bin/sh -c "cd /mnt && ./build.sh -v"

    after_script:
        - ./deploy.sh

    environment:
        name: ci
        url: https://sourceforge.net/projects/eloquentos/files/ci/$CI_PIPELINE_ID.iso/download

release:
    stage: deploy

    when: manual

    only:
        - tags

    before_script:
        - apt-get update
        - apt-get install -y sshpass

    script: ./release.sh

    environment:
        name: release
        url: https://sourceforge.net/projects/eloquentos/files/releases/$CI_COMMIT_TAG.iso/download