sudo: required

env:
    - secure: "YcvNjThblH8z5uVWru0Q32ZTtJ6EAfX1qfBcjhfqskXPWeaRhbQbiZU6OXjxbR7Suj0SAAyN9PiAApgyuY9uC7YJxfpb1CYQPnp/kg25kuSM+RggDKhliYLBtc4uIIb+UWoyAJWKnqljH0wiTNuefo+iE4J6aOJ5oC+s7py7KAhbgmtqLIXD94PQrOVQsj/8K+ERsjDSX2oZ5wUSVMtoY7Dp0HMyOZeDMwAjAqXCu/F24AkLtii2td8eMPEmmvm8VUO1iZu9GNrAGElMaFnJPLhBeFuVGjACwVvEasBHUVfsxIqmn+ZROu5I6npWSkNEQrBeoQ2PbLp6Kta8LTb9pAFQe0CpM1knOWCHryZFG//fzxxI5gWRREFxyB6mL42KFSaJA/z2Vrwgp1OQvRqGXsIQzfTowy6b9WozzGOpqYlJ7TLmEhp+/OZfNueOks5XKEwoWzjT7ztjQCnCvvM+VKjMsEPB/7FdcLO2iLCgkka60Rv95C4OndKfaEZG3+DG+MxqczO9HAYmB4JDMD0bnSjGTx38TbS4S/h6xIkiDpa05OxuGAC0H7vNbPkIr6ykqVMTzYb8fj9igex1DQgHN8aECQcr+yVHM8KOaJqT2/2Aek5M7BMJXOe+ofVkOxe2iseIXA4FOpWYr6ACT9/lNEMcLEVbGKUy5WGttNo7NRM="

services:
  - docker

before_install:
    - docker pull pritunl/archlinux
    - docker run --name eloquentos -itd --privileged -v ${PWD}:/mnt pritunl/archlinux /bin/bash
    - docker exec eloquentos pacman -S archiso --noconfirm
    - docker exec eloquentos pacman-key --add /mnt/sign-key
    - docker exec eloquentos pacman-key --lsign-key eloquentos@nimbusoft.co.uk
    - docker exec eloquentos mkdir /run/shm

script: docker exec eloquentos /bin/sh -c "cd /mnt && ./build.sh -v"

after_success:
    - sudo apt-get install -y sshpass
    - ./deploy.sh
