sudo: required

services:
  - docker

before_install:
    - docker pull pritunl/archlinux
    - docker run --name eloquentos -v ${PWD}:/mnt pritunl/archlinux /bin/bash
    - docker exec -d eloquentos 'pacman -Sy archiso'

script: docker exec -d eloquentos '/bin/sh -c "cd /mnt && ./build.sh -v"'
