sudo: required

services:
  - docker

before_install:
    - docker pull pritunl/archlinux
    - docker run --name eloquentos -t -v ${PWD}:/mnt pritunl/archlinux /bin/bash
    - docker start eloquentos
    - docker exec -i -d eloquentos 'pacman -Sy archiso'

script: docker exec -i -d eloquentos '/bin/sh -c "cd /mnt && ./build.sh -v"'
